# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\anaconda\envs\pyqtenv\project\netterminal-master(new)\netterminal-master\Forms\MainWindowMin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowMin(object):
    def setupUi(self, MainWindowMin):
        MainWindowMin.setObjectName("MainWindowMin")
        MainWindowMin.resize(413, 134)
        self.centralwidget = QtWidgets.QWidget(MainWindowMin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(284, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LedObjLabelMin = QtWidgets.QLabel(self.centralwidget)
        self.LedObjLabelMin.setMaximumSize(QtCore.QSize(200, 30))
        self.LedObjLabelMin.setText("")
        self.LedObjLabelMin.setObjectName("LedObjLabelMin")
        self.verticalLayout.addWidget(self.LedObjLabelMin)
        self.LedOptionsComboBoxMin = QtWidgets.QComboBox(self.centralwidget)
        self.LedOptionsComboBoxMin.setMaximumSize(QtCore.QSize(200, 30))
        self.LedOptionsComboBoxMin.setObjectName("LedOptionsComboBoxMin")
        self.verticalLayout.addWidget(self.LedOptionsComboBoxMin)
        self.LedConfirmPushButtonMin = QtWidgets.QPushButton(self.centralwidget)
        self.LedConfirmPushButtonMin.setMinimumSize(QtCore.QSize(100, 0))
        self.LedConfirmPushButtonMin.setMaximumSize(QtCore.QSize(100, 30))
        self.LedConfirmPushButtonMin.setObjectName("LedConfirmPushButtonMin")
        self.verticalLayout.addWidget(self.LedConfirmPushButtonMin)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.TimeObjLabelMin = QtWidgets.QLabel(self.centralwidget)
        self.TimeObjLabelMin.setText("")
        self.TimeObjLabelMin.setObjectName("TimeObjLabelMin")
        self.gridLayout.addWidget(self.TimeObjLabelMin, 1, 0, 1, 1)
        MainWindowMin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowMin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 413, 22))
        self.menubar.setObjectName("menubar")
        MainWindowMin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowMin)
        self.statusbar.setObjectName("statusbar")
        MainWindowMin.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowMin)
        QtCore.QMetaObject.connectSlotsByName(MainWindowMin)

    def retranslateUi(self, MainWindowMin):
        _translate = QtCore.QCoreApplication.translate
        MainWindowMin.setWindowTitle(_translate("MainWindowMin", "MainWindow"))
        self.LedConfirmPushButtonMin.setText(_translate("MainWindowMin", "确认"))
